

services:
  postgres:
    image: postgres:15
    container_name: usa_jobs_db
    environment:
      POSTGRES_DB: usa_jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usa_jobs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s



volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge